apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-dev
    spec:
      containers:
        - name: demo-dev
          image: registry.cn-beijing.aliyuncs.com/bmwpoc/demo-dev:$version$
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
      imagePullSecrets:
        - name: bmwpoc